# frozen_string_literal: true

# Example: production-style use of the rivescript-rb gem via Bundler.
#
# From this directory:
#   bundle install
#   bundle exec ruby hello.rb
#   bundle exec riveshell

source "https://rubygems.org"

gem "rivescript-rb", path: "../.."
